config/routes.rb
SimplePages::Engine.routes.draw do
  resources :pages
end

app/models/simple_pages/page.rb
module SimplePages
  class Page < ActiveRecord::Base
    self.table_name = SimplePages.page_table_name

    validates :title, presence: true

    scope :published, lambda { where('published_at <= ?', Time.zone.now) }
    scope :layout_at, lambda { |location| where(layout_at: location) }

    def layout_at=(values)
      if values.blank?
        super nil
      else
        super values
      end
    end

    SimplePages.page_modules.each { |module_name| include module_name }
  end
end

app/controllers/simple_pages/application_controller.rb
module SimplePages
  class ApplicationController < ActionController::Base
    respond_to :html

    helper ::RailsTheme::Engine.helpers
    helper SimplePages.helper_modules

    SimplePages.controller_modules.each { |module_name| include module_name }

    if SimplePages.extra_page_layout.present?
      has_page_layout_at SimplePages.extra_page_layout
    end
  end
end

app/controllers/simple_pages/pages_controller.rb
require_dependency 'simple_pages/application_controller'

module SimplePages
  class PagesController < ApplicationController
    before_filter :authenticate_session!, except: [:show]

    load_resource class: 'SimplePages::Page', only: [:index]
    before_filter :new_page, only: [:new, :create]
    load_resource class: 'SimplePages::Page', find_by: :url, only: [:show, :edit, :update, :destroy]

    authorize_resource class: 'SimplePages::Page', except: [:show]

    def index
      @pages = @pages.paginate pagination_options
      respond_with @pages
    end

    def show
      respond_with @page
    end

    def new
      @page.author = session_user
      respond_with @page
    end

    def edit
    end

    def create
      @page.save
      respond_with @page
    end

    def update
      @page.update_attributes page_params
      respond_with @page
    end

    def destroy
      @page.destroy
      respond_with @page
    end

    protected

    def page_params
      if params.respond_to? :permit and params.has_key? :page
        params.require(:page).permit(SimplePages.permitted_fields)
      else
        params[:page]
      end
    end

    def new_page
      @page = SimplePages::Page.new page_params
    end

    private

    def pagination_options
      { page: params[:page], per_page: SimplePages.pages_per_page }
    end
  end
end

app/helpers/simple_pages/application_helper.rb
module SimplePages
  module ApplicationHelper
  end
end

app/helpers/simple_pages/pages_helper.rb
module SimplePages
  module PagesHelper
    def publish_time(published_at, updated_at)
      return unless published_at
      options = {
        datetime: published_at,
        pubdate: true,
        :'data-updated' => (updated_at != published_at ? 'true' : nil ),
        class: 'published_at'
      }
      content_tag :time, ::I18n.l(published_at, format: :long), options
    end

    def author_vcard(author)
      content_tag :span, class: 'author vcard' do
        t('helpers.posted_by', name: content_tag(:span, author)).html_safe
      end
    end

    def selected_page_author(object)
      object.author.try :simple_page_owner_option
    end

    def local_published_at(object)
      object.published_at? ? object.published_at.localtime : nil
    end

    def page_author_options
      ::User.unscoped.map do |author|
        [author.name, author.simple_page_owner_option]
      end
    end

    def page_cluster_options
      ::Role.enabled.map do |role|
        [t(role.name, scope: 'roles.names'), role.name]
      end
    end

    def page_layout_at_options
      page_layout_at.map do |key|
        [t(key, scope: 'simple_pages.layout_at'), key]
      end
    end
  end
end

app/views/layouts/simple_pages/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title><%= t('site.title') %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="<%= t('site.author') %>">

  <link rel="shortcut icon" href="/favicon.ico">

  <%= stylesheet_link_tag 'simple_pages/application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'application/chromeframe' %>

  <header class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <%= render 'application/header' %>
      </div>
    </div>
  </header>

  <div role="main" id="main" class="container-fluid">
    <aside role="flash_messages" class="row-fluid">
      <%= render 'application/flash_messages' %>
    </aside>
    <div class="row-fluid">
      <div class="span12 <%= controller_name %>">
        <%= yield %>
      </div>
    </div>
  </div>

  <footer id="bigfoot" class="container-fluid">
    <div class="row-fluid">
      <%= render 'application/footer' %>
    </div>
  </footer>

  <%= javascript_include_tag "simple_pages/application" %>
  <%= render 'application/google_analytics' if Rails.env.production? %>
</body>
</html>

app/views/simple_pages/pages/_form.html.erb
<div class="form-inputs">
  <% if can? :update_url, f.object %>
    <%= f.input :url, input_html: { class: 'span10' } %>
  <% end %>
  <%= f.input :title, input_html: { class: 'span10' } %>
  <%= f.input :excerpt,
    as: :text,
    input_html: {
      rows: 5,
      class: 'span10'
    } %>
  <%= f.input :content, input_html: { class: 'ckeditor' } %>
  <%= f.input :owner,
    collection: page_author_options,
    selected: selected_page_author(f.object),
    input_html: {
      class: 'chzn-select'
    } %>
  <%= f.input :published_at,
    as: :string,
    input_html: {
      value: local_published_at(f.object),
      class: 'datetimepicker'
    } %>
  <%= f.input :layout_at,
    as: :select,
    collection: page_layout_at_options,
    include_blank: false %>
  <%= f.input :cluster,
    as: :select,
    collection: page_cluster_options,
    input_html: {
      multiple: true,
      class: 'chzn-select'
    } %>
</div>

app/views/simple_pages/pages/_table.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= SimplePages::Page.human_attribute_name(:title) %></th>
      <th><%= SimplePages::Page.human_attribute_name(:layout_at) %></th>
      <th><%= SimplePages::Page.human_attribute_name(:author) %></th>
      <th><%= SimplePages::Page.human_attribute_name(:published_at) %></th>
      <th><%= t('helpers.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= t(page.layout_at, scope: 'simple_pages.layout_at') if page.layout_at? %></td>
        <td><%= page.author.name %></td>
        <td><%= publish_time(page.published_at, page.updated_at) %></td>
        <td class="actions">
          <%= render_btn_group do |btn|
            if can? :show, page
              btn << link_to_show(page_path(page))
            end
            if can? :edit, page
              btn << link_to_edit(edit_page_path(page))
            end
            if can? :destroy, page
              btn << link_to_destroy(page_path(page))
            end
          end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/simple_pages/pages/edit.html.erb
<article>
  <header>
    <h1><%= t('.title') %></h1>
  </header>

  <%= render_list class: 'nav nav-tabs' do |li|
    if can? :index, SimplePages::Page
      li << [link_to(t('helpers.index'), pages_path), { class: 'pull-right' }]
    end
    if can? :show, @page
      li << [link_to(t('helpers.show'), @page), { class: 'pull-right' }]
    end
  end %>

  <div>
    <%= simple_form_for @page, as: :page, html: { class: 'form-horizontal' } do |f| %>
      <%= f.error_notification %>
      <%= render 'form', f: f %>
      <div class="form-actions">
        <%= submit_button f %>
      </div>
    <% end %>
  </div>

  <footer>
  </footer>
</article>

app/views/simple_pages/pages/index.html.erb
<article>
  <header>
    <h1><%= t('.title') %></h1>
  </header>

  <%= render_list class: 'nav nav-tabs' do |li|
    if can? :new, SimplePages::Page
      li << [link_to(t('helpers.new'), new_page_path), { class: 'pull-right' }]
    end
  end %>

  <%= render 'table', pages: @pages %>

  <footer>
    <%= render 'application/pagination', collection: @pages %>
  </footer>
</article>

app/views/simple_pages/pages/new.html.erb
<article>
  <header>
    <h1><%= t('.title') %></h1>
  </header>

  <%= render_list class: 'nav nav-tabs' do |li|
    if can? :index, SimplePages::Page
      li << [link_to(t('helpers.index'), pages_path), { class: 'pull-right' }]
    end
  end %>

  <div>
    <%= simple_form_for @page, as: :page, html: { class: 'form-horizontal' } do |f| %>
      <%= f.error_notification %>
      <%= render 'form', f: f %>
      <div class="form-actions">
        <%= submit_button f %>
      </div>
    <% end %>
  </div>

  <footer>
  </footer>
</article>

app/views/simple_pages/pages/show.html.erb
<article>
  <header>
    <h1><%= @page.title %></h1>
  </header>

  <%= render_list class: 'nav nav-tabs' do |li|
    li << [author_vcard(@page.author.name), { class: 'hidden' }]
    li << [publish_time(@page.created_at, @page.updated_at), { class: 'meta hidden' }]
    if signed_in?
      if can? :index, SimplePages::Page
        li << [link_to(t('helpers.index'), pages_path), { class: 'pull-right' }]
      end
      if can? :edit, @page
        li << [link_to(t('helpers.edit'), edit_page_path(@page)), { class: 'pull-right' }]
      end
    end
  end %>

  <div>
    <%= simple_format @page.excerpt %>
    <%= @page.content.html_safe if @page.content %>
  </div>

  <footer>
  </footer>
</article>